SHOW DATABASES;

USE ABHINAV;

CREATE TABLE STUDENTS (
ID INT NOT NULL,
NAME VARCHAR(20) NOT NULL,
EMAIL VARCHAR(20),
PHONE VARCHAR(20),
PRIMARY KEY (ID)
);

CREATE TABLE LIBRARY(
BID INT NOT NULL,
BNAME VARCHAR(20),
IDATE DATETIME DEFAULT NOW(),
ID INT NOT NULL,
PRIMARY KEY (BID),
FOREIGN KEY (ID) REFERENCES STUDENTS (ID)
);

INSERT INTO STUDENTS 
VALUES (1,'ABHINAV','ABHINAV@GMAIL.COM','87878787');


INSERT INTO STUDENTS 
VALUES (2,'AMAN','AMAN@GMAIL.COM','852125874');

INSERT INTO STUDENTS 
VALUES (3,'AKASH','AKASH@GMAIL.COM','741258963');

INSERT INTO STUDENTS 
VALUES (4,'GAURAV','GAURAV@GMAIL.COM','789456123');

SELECT * FROM STUDENTS;

ALTER TABLE LIBRARY
DROP COLUMN IDATE;

INSERT INTO LIBRARY
VALUES (101,'MATHS',1);

INSERT INTO LIBRARY
VALUES (102,'ENGLISH',1);

INSERT INTO LIBRARY
VALUES (103,'PHYSICS',1);

INSERT INTO LIBRARY
VALUES (104,'CHEMISTRY',1);

SELECT * FROM LIBRARY;

SELECT * FROM STUDENTS;

SELECT LIBRARY.BID , LIBRARY.BNAME , LIBRARY.ID , STUDENTS.NAME , STUDENTS.EMAIL
FROM LIBRARY
INNER JOIN STUDENTS
ON LIBRARY.ID = STUDENTS.ID;

CREATE TABLE ORDERS(
ID INT NOT NULL,
OID INT NOT NULL,
ONAME VARCHAR(50),
PRIMARY KEY (OID),
FOREIGN KEY (ID) references STUDENTS(ID)
);

INSERT INTO ORDERS
VALUES (1,1,'12AA12');

INSERT INTO ORDERS
VALUES (1,2,'12AA14'); 

SELECT * FROM STUDENTS;

SELECT * FROM ORDERS;


SELECT STUDENTS.NAME , STUDENTS.ID , ORDERS.ONAME
FROM ORDERS
INNER JOIN STUDENTS
ON STUDENTS.ID = ORDERS.ID
INNER JOIN LIBRARY
ON LIBRARY.ID = STUDENTS.ID;

SELECT * FROM LIBRARY;

CREATE TABLE RES(
ID INT NOT NULL,
NAME VARCHAR(50),
PLACE VARCHAR(20),
PRIMARY KEY (ID)
);

INSERT INTO RES
VALUES (1,'ABHINAV','DARBHANGA');

INSERT INTO RES 
VALUES (2,'AJAY','LUCKNOW');

INSERT INTO RES
VALUES (3,'AMAN','DELHI');

INSERT INTO RES
VALUES (4,'AKASH','VSKP');

INSERT INTO RES
VALUES (5,'MOHAN','RANCHI');


SELECT * FROM RES;

CREATE TABLE WAITER(
WID INT NOT NULL,
WNAME VARCHAR(50),
ID INT NOT NULL,
PRIMARY KEY(WID),
FOREIGN KEY (ID) REFERENCES RES(ID) 
);

INSERT INTO WAITER
VALUES (1,'MILLER',1);


INSERT INTO WAITER
VALUES (2,'JAGDEEP',1);


INSERT INTO WAITER
VALUES (3,'MILLER',4);


INSERT INTO WAITER
VALUES (4,'JOHN',3);


INSERT INTO WAITER
VALUES (5,'HAMID',2);

SELECT * FROM RES;
SELECT * FROM WAITER;

SELECT WAITER.WNAME,RES.ID,RES.NAME,RES.PLACE
FROM WAITER
INNER JOIN RES 
ON WAITER.ID = RES.ID;

SELECT * FROM RES
WHERE RES.NAME LIKE 'ABHINAV%';

SELECT DISTINCT RES.PLACE
FROM RES;

SELECT * FROM RES
WHERE PLACE LIKE 'DARBHANGA%';

INSERT INTO RES
VALUES (6,'HARSH','DARBHANGA');

SELECT * FROM RES
WHERE RES.PLACE LIKE 'DARBHANGA%';