SHOW DATABASES;

CREATE DATABASE D1;

USE D1;

CREATE TABLE CUSTOMERS(
ID INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(55),
AGE INT,
ADDRESS VARCHAR(50),
SALARY INT ,
PRIMARY KEY (ID)
);

INSERT INTO CUSTOMERS (NAME,AGE,ADDRESS,SALARY)
VALUES ('RAMESH',32,'AHEMDABAD',2000);


INSERT INTO CUSTOMERS (NAME,AGE,ADDRESS,SALARY)
VALUES ('Khilan',25,'Delhi',2500);


INSERT INTO CUSTOMERS (NAME,AGE,ADDRESS,SALARY)
VALUES ('kaushik',23,'Kota',200);


INSERT INTO CUSTOMERS (NAME,AGE,ADDRESS,SALARY)
VALUES ('Chaitali',16,'MUMBAI',2500);


INSERT INTO CUSTOMERS (NAME,AGE,ADDRESS,SALARY)
VALUES ('Hardik',18,'MP',2700);


INSERT INTO CUSTOMERS (NAME,AGE,ADDRESS,SALARY)
VALUES ('Komal',22,'INDORE',2900);


INSERT INTO CUSTOMERS (NAME,AGE,ADDRESS,SALARY)
VALUES ('Muffy',15,'AHEMDABAD',2000);

SELECT * FROM CUSTOMERS;

SELECT ID , NAME , AGE FROM CUSTOMERS;

SELECT * FROM CUSTOMERS
WHERE SALARY>2000;

SELECT * FROM CUSTOMERS 
WHERE AGE>20 AND SALARY > 2000;

SELECT * FROM CUSTOMERS
WHERE AGE = 18 OR ID%2=0;

UPDATE CUSTOMERS 
SET NAME = 'AMITESH NAYAK'
WHERE ID = 1;

SELECT * FROM CUSTOMERS
WHERE ID = 1;

INSERT INTO CUSTOMERS (NAME,AGE,ADDRESS,SALARY)
VALUES ('MANOJ PATHAK',23,'Kota',200);

SELECT * FROM CUSTOMERS;

SELECT * FROM CUSTOMERS
WHERE ID = 9;

DELETE FROM CUSTOMERS
WHERE ID = 9;

SELECT * FROM CUSTOMERS;

SELECT * FROM CUSTOMERS
WHERE SALARY LIKE '2__0';

SELECT * FROM CUSTOMERS
LIMIT 3;

SELECT * FROM CUSTOMERS
ORDER BY NAME;

SELECT * FROM CUSTOMERS 
ORDER BY ID;

CREATE TABLE ORDERS(
OID INT NOT NULL AUTO_INCREMENT,
CID INT NOT NULL,
AMOUNT INT NOT NULL,
PRIMARY KEY (OID),
FOREIGN KEY (CID) references CUSTOMERS(ID)
);

INSERT INTO ORDERS (CID,AMOUNT)
VALUES (2,2000);

INSERT INTO ORDERS (CID,AMOUNT)
VALUES (1,200);

INSERT INTO ORDERS (CID,AMOUNT)
VALUES (5,500);

INSERT INTO ORDERS (CID,AMOUNT)
VALUES (6,550);

SELECT * FROM ORDERS;

SELECT CUSTOMERS.NAME,ORDERS.AMOUNT,CUSTOMERS.ID
FROM ORDERS
INNER JOIN CUSTOMERS
ON CUSTOMERS.ID = ORDERS.CID; 


SELECT CUSTOMERS.NAME,ORDERS.AMOUNT,CUSTOMERS.ID
FROM ORDERS
LEFT JOIN CUSTOMERS
ON CUSTOMERS.ID = ORDERS.CID; 


SELECT CUSTOMERS.NAME,ORDERS.AMOUNT,CUSTOMERS.ID
FROM ORDERS
RIGHT JOIN CUSTOMERS
ON CUSTOMERS.ID = ORDERS.CID; 


SELECT CUSTOMERS.NAME,ORDERS.AMOUNT,CUSTOMERS.ID
FROM ORDERS
LEFT JOIN CUSTOMERS
ON CUSTOMERS.ID = ORDERS.CID
UNION
SELECT CUSTOMERS.NAME,ORDERS.AMOUNT,CUSTOMERS.ID
FROM ORDERS
RIGHT JOIN CUSTOMERS
ON CUSTOMERS.ID = ORDERS.CID; 

